name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtscript qtwebengine'

    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile -before -o CaptureStream
      shell: /bin/bash -e {0}
      env:
      Qt5_Dir: /home/runner/work/CaptureStream/Qt/5.12.9/gcc_64
      Qt5_DIR: /home/runner/work/CaptureStream/Qt/5.12.9/gcc_64
      QT_PLUGIN_PATH: /home/runner/work/CaptureStream/Qt/5.12.9/gcc_64/plugins
      QML2_IMPORT_PATH: /home/runner/work/CaptureStream/Qt/5.12.9/gcc_64/qml
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
