name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make

    - name: framework_osx_x86_64
      run: ./_framework_osx_x86_64.sh
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./

