name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtscript qtwebengine'

    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile -before -o CaptureStream
    - name: make
      run: make CaptureStream
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
