name: C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: macos-11

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v3
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
      
    - name: Make CS-English executable
      run: sudo chmod -R 755 ./CS-English.app
  
    - uses: actions/upload-artifact@v3
      with:
        name: CS-English
        path: ./

