name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtscript qtwebengine'

    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile -Wall -before
    - name: make
      run: make
    - name: Download artifact to get url to upload to release
      uses: actions/download-artifact@v2
