name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latst

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.5.1
        modules: 'qtcharts qtscript qtwebengine'
        arch: win32_mingw32

    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile -Wall -before
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./

