name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.4
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v2
      with:
        name: CaptureStream
        path: ./

